DROP TABLE IF EXISTS PESSOA;

CREATE TABLE PESSOA(
ID_PESSOA SERIAL PRIMARY KEY NOT NULL,
NOME VARCHAR(300) NOT NULL,
TIPO VARCHAR(2) NOT NULL,
NUM_DOCUMENTO VARCHAR(300) NOT NULL,
SCORE INTEGER NOT NULL
);

INSERT INTO PESSOA(NOME,TIPO,NUM_DOCUMENTO,SCORE) VALUES('Fernando Galdino','PF','01354223373',2);
INSERT INTO PESSOA(NOME,TIPO,NUM_DOCUMENTO,SCORE) VALUES('Amelia Gomes','PF','01265745888',9);
INSERT INTO PESSOA(NOME,TIPO,NUM_DOCUMENTO,SCORE) VALUES('Mundo Pet LTDA','PJ','48447654000194',5);

DROP TABLE IF EXISTS CONTA_CORRENTE;

CREATE TABLE CONTA_CORRENTE(
  ID_CONTA SERIAL PRIMARY KEY NOT NULL,
  NUMERO INTEGER UNIQUE NOT NULL,
  AGENCIA INTEGER NOT NULL,
  TIPO VARCHAR(1) NOT NULL,
  ID_PESSOA INTEGER NOT NULL,
  CONSTRAINT FK1_CONTA_CORRENTE FOREIGN KEY (ID_PESSOA)
      REFERENCES PESSOA (ID_PESSOA) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION        
);

INSERT INTO CONTA_CORRENTE(NUMERO,AGENCIA,TIPO,ID_PESSOA) VALUES(111111,3755,'C',1);
INSERT INTO CONTA_CORRENTE(NUMERO,AGENCIA,TIPO,ID_PESSOA) VALUES(222222,3755,'C',2);
INSERT INTO CONTA_CORRENTE(NUMERO,AGENCIA,TIPO,ID_PESSOA) VALUES(333333,3755,'E',3);