DROP TABLE IF EXISTS CARTEIRA;
DROP TABLE IF EXISTS CONTA_CORRENTE;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS AUTH;

CREATE TABLE PESSOA(
ID_PESSOA SERIAL PRIMARY KEY NOT NULL,
NOME VARCHAR(300) NOT NULL,
TIPO VARCHAR(2) NOT NULL,
NUM_DOCUMENTO VARCHAR(300) NOT NULL,
SCORE INTEGER NOT NULL
);

INSERT INTO PESSOA(NOME,TIPO,NUM_DOCUMENTO,SCORE) VALUES('Fernando Galdino','PF','01554223378',2);
INSERT INTO PESSOA(NOME,TIPO,NUM_DOCUMENTO,SCORE) VALUES('Amelia Gomes','PF','01265745888',9);
INSERT INTO PESSOA(NOME,TIPO,NUM_DOCUMENTO,SCORE) VALUES('Mundo Pet LTDA','PJ','48447654000194',5);


CREATE TABLE CONTA_CORRENTE(
  ID_CONTA SERIAL PRIMARY KEY NOT NULL,
  NUMERO INTEGER UNIQUE NOT NULL,
  AGENCIA INTEGER NOT NULL,
  TIPO VARCHAR(1) NOT NULL,
  ID_PESSOA INTEGER NOT NULL,
  CONSTRAINT FK1_CONTA_CORRENTE FOREIGN KEY (ID_PESSOA)
      REFERENCES PESSOA (ID_PESSOA) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION        
);

INSERT INTO CONTA_CORRENTE(NUMERO,AGENCIA,TIPO,ID_PESSOA) VALUES(111111,3755,'C',1);
INSERT INTO CONTA_CORRENTE(NUMERO,AGENCIA,TIPO,ID_PESSOA) VALUES(222222,3755,'C',2);
INSERT INTO CONTA_CORRENTE(NUMERO,AGENCIA,TIPO,ID_PESSOA) VALUES(333333,3755,'E',3);


CREATE TABLE CARTEIRA(
  ID_CARTEIRA SERIAL PRIMARY KEY NOT NULL,
  LIMITE_CE NUMERIC(22,2) NOT NULL,
  LIMITE_CC NUMERIC(22,2) NOT NULL,
  ID_CONTA INTEGER NOT NULL,
  CONSTRAINT FK1_CARTEIRA FOREIGN KEY (ID_CONTA)
      REFERENCES CONTA_CORRENTE (ID_CONTA) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION        
);

INSERT INTO CARTEIRA(LIMITE_CE,LIMITE_CC,ID_CONTA) VALUES(1000.00,200.00,1);
INSERT INTO CARTEIRA(LIMITE_CE,LIMITE_CC,ID_CONTA) VALUES(5000.00,15000.00,2);
INSERT INTO CARTEIRA(LIMITE_CE,LIMITE_CC,ID_CONTA) VALUES(1000.00,200.00,3);

CREATE TABLE AUTH(
ID SERIAL PRIMARY KEY NOT NULL,
USERNAME VARCHAR(300) NOT NULL,
PASSWORD VARCHAR(300) NOT NULL,
ACTIVE BOOLEAN,
ROLES VARCHAR(300) NOT NULL
);

INSERT INTO AUTH(USERNAME,PASSWORD,ROLES) VALUES('user','pass','ROLE_USER');