version: '3'
services:
  db:
    image: "postgres"
    ports:
     - "5432:5432"
    environment:
     POSTGRES_DB: db
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
  
  app:
    build: .
    ports:
     - "8080:8080"
    environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://db/db
     SPRING_DATASOURCE_USERNAME: admin
     SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
     - db