# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine

# Copy jar file
COPY desafio-java-banco-0.0.1-SNAPSHOT.jar /desafio-java-banco-0.0.1-SNAPSHOT.jar

# run the jar
CMD ["/usr/bin/java", "-jar", "/desafio-java-banco-0.0.1-SNAPSHOT.jar"]